services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aivacol-sqlserver

    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Aivacol@123'

    ports:
      - '1433:1433'

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aivacol-redis

    ports:
      - '6379:6379'

    restart: unless-stopped

volumes:
  sqlserver_data:
